export const courierNames = [
  'CJ 대한통운',
  '롯데택배',
  '한진택배',
  '우체국',
  '로젠택배',
  'CJ대한통운특송',
  '대한통운',
  '업체직송',
  '경동택배',
  '대신택배',
  '우체국 EMS',
  'GSM NtoN',
  '에어보이익스프레스',
  'CVS택배',
  '일양택배',
  '합동택배',
  '롯데글로벌',
  'ACI Express',
  '스마트로지스',
  'FEDEX',
  'LX Pantos',
  '씨웨이',
  '브리지로지스',
  '건영택배',
  'BGF포스트',
  'GSI익스프레스',
  'SLX택배',
  '농협택배',
  '시알로지텍',
  'DHL GlobalMail',
  'ACE Express',
  '아주택배',
  '성원글로벌',
  '우리택배',
  '워펙스',
  'DHL',
  '큐익스프레스',
  '2FastsExpress',
  '로지스밸리택배',
  'LineExpress',
  '용마로지스',
  '한의사랑택배',
  'UPS',
  'TNT',
  'USPS',
  '홈픽택배',
  'CJ생수',
  '하우저',
  '은하쉬핑',
  'ECMS익스프레스',
  '로토스',
  '두발히어로(4시간당일택배)',
  '우리동네택배',
  '애니트랙',
  '홈이노베이션로지스',
  '대운글로벌',
  '에스더쉬핑',
  'J-NET',
  'SFC(Santai)',
  'KGL네트웍스',
  '한샘',
  'elianpost',
  '굿투럭',
  '판아시아',
  '유프레이트 코리아',
  'GTS로지스',
  '유진로지스틱스',
  '1004홈',
  'ARAMEX',
  'BISNZ',
  'CLS',
  'EFS',
  'FLEXPORT',
  'HY',
  'Hubnet Logistics',
  'ICS',
  'IK물류',
  'LG전자',
  'LTL',
  'NEXEN직배송',
  'NK로지솔루션',
  'SBGLS',
  'SC로지스',
  'SINOTRANS EXPRESS',
  'YDH',
  'acccargo',
  'cainiao',
  'i-parcel',
  'ibpcorp',
  'kt express',
  'ocs코리아',
  'yjs글로벌',
  'yunda express',
  '嘉里大榮',
  '고박스',
  '골드스넵스',
  '국제익스프레스',
  '나은물류',
  '다다스마트',
  '대림통운',
  '더바오',
  '도도플렉스',
  '든든택배',
  '딜리래빗',
  '딜리박스',
  '라스트마일시스템즈',
  '로지스밸리',
  '로지스파트너',
  '로지스팟',
  '롯데칠성',
  '모든로지스',
  '물류대장LCS',
  '바바바로지스',
  '반품구조대',
  '발렉스',
  '배송하기좋은날',
  '벤더피아',
  '부릉',
  '삼다수가정배송',
  '삼성SDS',
  '삼성로지텍',
  '삼성에어컨직배송',
  '서림물류',
  '성훈물류',
  '세방택배',
  '스파클직배송',
  '아르고',
  '에이씨티앤코아물류',
  '에이치케이홀딩스',
  '에코하이',
  '엔티엘피스',
  '엘서비스',
  '엠티인터네셔벌',
  '오늘의픽업',
  '오늘회러쉬',
  '올타코리아',
  '와이드테크',
  '우진인터로지스',
  '우편등기',
  '웅지익스프레스',
  '원더스퀵',
  '위무브',
  '윈핸드해운상공',
  '유로택배',
  '이노스',
  '이스트라',
  '이투마스',
  '인터로지스',
  '자이언트',
  '제1화물',
  '제니엘시스템',
  '제이로지스트',
  '지니고',
  '지디에이코리아',
  '지비에스',
  '지씨에스',
  '지에이치스피드',
  '직구문',
  '천일특송',
  '캐나다쉬핑',
  '컬리넥스트마일',
  '케이제이티',
  '큐런',
  '큐브플로우',
  '탱고앤고',
  '토나미',
  '투데이',
  '티에스지로지스',
  '팀프레시',
  '패스트박스',
  '팬스타국제특송',
  '팬스타국제특송(deprecated)',
  '퍼레버택배',
  '풀무원샘물',
  '풀앳홈',
  '프레시메이트',
  '프레시솔루션',
  '핑퐁',
  '하이브시티',
  '한미포스트',
  '한진국제특송',
  '허싱카고코리아',
  '현대글로비스',
  '홈픽오늘도착',
  '화물부탁해',
  '화통',
  '후쿠야마통운',
];

export const courierCode = {
  롯데택배: 'HYUNDAI',
  로젠택배: 'KGB',
  우체국: 'EPOST',
  한진택배: 'HANJIN',
  CJ대한통운: 'CJGLS',
  경동택배: 'KDEXP',
  업체직송: 'DIRECT',
  일양택배: 'ILYANG',
  천일특송: 'CHUNIL',
  아주택배: 'AJOU',
  SC로지스: 'CSLOGIS',
  대신택배: 'DAESIN',
  CVS택배: 'CVS',
  합동택배: 'HDEXP',
  DHL: 'DHL',
  UPS: 'UPS',
  FEDEX: 'FEDEX',
  우편등기: 'REGISTPOST',
  '우체국 EMS': 'EMS',
  TNT: 'TNT',
  USPS: 'USPS',
  'i-parcel': 'IPARCEL',
  'GSM NtoN': 'GSMNTON',
  성원글로벌: 'SWGEXP',
  범한판토스: 'PANTOS',
  'ACI Express': 'ACIEXPRESS',
  대운글로벌: 'DAEWOON',
  에어보이익스프레스: 'AIRBOY',
  KGL네트웍스: 'KGLNET',
  건영택배: 'KUNYOUNG',
  SLX택배: 'SLX',
  우리택배: 'HONAM',
  LineExpress: 'LINEEXPRESS',
  '2FastsExpress': 'TWOFASTEXP',
  한의사랑택배: 'HPL',
  굿투럭: 'GOODSTOLUCK',
  CJ대한통운특송: 'KOREXG',
  한덱스: 'HANDEX',
  BGF: 'BGF',
  ECMS익스프레스: 'ECMS',
  원더스퀵: 'WONDERS',
  용마로지스: 'YONGMA',
  세방택배: 'SEBANG',
  농협택배: 'NHLOGIS',
  롯데글로벌: 'LOTTEGLOBAL',
  GSI익스프레스: 'GSIEXPRESS',
  EFS: 'EFS',
  'DHL GlobalMail': 'DHLGLOBALMAIL',
  GPS로직: 'GPSLOGIX',
  시알로지텍: 'CRLX',
  브리지로지스: 'BRIDGE',
  홈이노베이션로지스: 'HOMEINNOV',
  씨웨이: 'CWAY',
  자이언트: 'GNETWORK',
  'ACE Express': 'ACEEXP',
  우리동네택배: 'WEVILL',
  퍼레버택배: 'FOREVERPS',
  워펙스: 'WARPEX',
  큐익스프레스: 'QXPRESS',
  스마트로지스: 'SMARTLOGIS',
  홈픽택배: 'HOMEPICK',
  GTS로지스: 'GTSLOGIS',
  에스더쉬핑: 'ESTHER',
  로토스: 'INTRAS',
  은하쉬핑: 'EUNHA',
  '유프레이트 코리아': 'UFREIGHT',
  엘서비스: 'LSERVICE',
  로지스밸리: 'TPMLOGIS',
  제니엘시스템: 'ZENIELSYSTEM',
  애니트랙: 'ANYTRACK',
  제이로지스트: 'JLOGIST',
  '두발히어로(4시간당일택배)': 'CHAINLOGIS',
  큐런: 'QRUN',
  프레시솔루션: 'FRESHSOLUTIONS',
  하이브시티: 'HIVECITY',
  한샘: 'HANSSEM',
  'SFC(Santai)': 'SFC',
  'J-NET': 'JNET',
  지니고: 'GENIEGO',
  판아시아: 'PANASIA',
  elianpost: 'ELIAN',
  롯데칠성: 'LOTTECHILSUNG',
  SBGLS: 'SBGLS',
  올타코리아: 'ALLTAKOREA',
  'yunda express': 'YUNDA',
  발렉스: 'VALEX',
  국제익스프레스: 'KOKUSAI',
  윈핸드해운항공: 'XINPATEK',
  탱고앤고: 'HEREWEGO',
  웅지익스프레스: 'WOONGJI',
  핑퐁: 'PINGPONG',
  YDH: 'YDH',
  화물부탁해: 'CARGOPLEASE',
  로지스팟: 'LOGISPOT',
  프레시메이트: 'FRESHMATES',
  부릉: 'VROONG',
  NK로지솔루션: 'NKLS',
  도도플렉스: 'DODOFLEX',
  이투마스: 'ETOMARS',
  배송하기좋은날: 'SHIPNERGY',
  벤더피아: 'VENDORPIA',
  캐나다쉬핑: 'COSHIP',
  지디에이코리아: 'GDAKOREA',
  바바바로지스: 'BABABA',
  팀프레시: 'TEAMFRESH',
  '1004홈': 'HOME1004',
  나은물류: 'NAEUN',
  acccargo: 'ACCCARGO',
  엔티엘피스: 'NTLPS',
  삼다수가정배송: 'EKDP',
  허싱카고코리아: 'HOTSINGCARGO',
  'SINOTRANS EXPRESS': 'SINOEX',
  딜리래빗: 'DRABBIT',
  홈픽오늘도착: 'HOMEPICKTODAY',
  대림통운: 'DAERIM',
  로지스파트너: 'LOGISPARTNER',
  고박스: 'GOBOX',
  패스트박스: 'FASTBOX',
  팬스타국제특송: 'PANSTAR',
};
